### ISSUE TITLE
BookReader Hypothesis support

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#1214]
Work with @hypothesis to make bookreader integration with the hypothesis client fully work.

Will need a well defined fragment schema so hypothesis can treat BR more like PDFs.

Planning:
- [ ] Create Selector spec for bookreader; discuss with Hypothesis folks
- [ ] Wire up hooks for hypothesis client to re-render on page load changes

Tasks:
- [ ] https://github.com/hypothesis/client/issues/5711

**Comment by mekarpeles** [comment]
Cross-referencing: the product-level umbrella for this (deep linking/saving/sharing clippings, per #1478) is now tracked at [openlibrary#13226](https://github.com/internetarchive/openlibrary/issues/13226) (Annotations / Sharable Snippets).
