### ISSUE TITLE
Use async/await instead of .then where appropriate

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#940]
Find all occurrences of `.then` in the codebase (there are 9 matching files) and replace them with `async`/`await` where it makes sense to do so. Read the notes here about why this improves code quality:  https://github.com/internetarchive/bookreader/wiki/JS-Modernization-Plan-Notes#uses-asyncawait-instead-of-then-where-appropriate

Note for simple cases like `.then(r => r.json())` , do _not_ convert those. Those are more legible like that then if we introduced a temporary variable.

Files containing `.then`; note not all of these might need changes!

- [x] `src/BookNavigator/bookmarks/ia-bookmarks.js`
    - [x] #952
    - [x] #961 One more spot remaining in `fetchUserBookmarks`
- [x] `src/plugins/tts/AbstractTTSEngine.js`#952
- [x]  `src/plugins/tts/FestivalTTSEngine.js` #958
- [x] `src/plugins/tts/WebTTSEngine.js`
    - [x] #952
    - [x] #961 `reload`, `finish`, `pause`, `_chromePausingBugFix`, 
- [x] `src/plugins/tts/PageChunk.js` #957
- [x] `src/plugins/tts/PageChunkIterator.js`#952
- [x] `src/plugins/plugin.chapters.js` #957
- [x] `src/plugins/plugin.text_selection.js` #958
- [x] `src/plugins/search/plugin.search.js` #957
- [x] `tests/jest/plugins/search/plugin.search.test.js` #958
- [x] `tests/jest/plugins/tts/AbstractTTSEngine.test.js` #958

**Comment by sancodes** [comment]
if no one is working on this, I'll help

**Comment by cdrini** [comment]
Go for it @sancodes !

**Comment by sancodes** [comment]
@cdrini Thank you, I will be glad to work on other tasks as well. I will get started on this task soon.

**Comment by padv** [comment]
Hi!

I went ahead and did some of the refactoring #951, but I will stop since @sancodes will be handling the rest. he may use some of my code if he wants to. Cheers!

**Comment by sancodes** [comment]
@cdrini not going to lie. Looking at the old code base is very frightening, given the limits I have in my coding experience. Especially, the promise chain, seems to be very complicated for me.
 I still tried my best, 
Please help me make sure if the code is working correctly. I am willing to work on any bug, for the changes I have made.

**Comment by cdrini** [comment]
No worries @padv ! Do you want to fix up the plugin.chapters.js file?

**Comment by sancodes** [comment]
@cdrini I will try to continue, to add modifications to remaining issues.

**Comment by sancodes** [comment]
@cdrini changes to 3 files, I have pushed for reviews. Please let me know, the mistakes, I have made, I'll correct it. Need heavy review on those files.

**Comment by sancodes** [comment]
@cdrini did some changes on the remaining files, please help me review them. Thank you.

**Comment by cdrini** [comment]
Awesome @sancodes ! I took another look around the codebase, and I think there are 4 places left that need updating :)

**Comment by sancodes** [comment]
@cdrini will try to tackle the remaining promises refactor

**Comment by sancodes** [comment]
@cdrini hello, can you help me take a look at my PR, and see if I need fix. Thank you.

**Comment by cdrini** [comment]
Woohoo! Thanks for you perseverance, @sancodes !

**Comment by sancodes** [comment]
@cdrini thank you. Please let me know if there's any task, I can tackle. 

I'm willing to help.
